### ISSUE TITLE
Initializing several VaultHttpClient cause duplicate "Accept" header

### ISSUE THREAD

**Issue by amitisss** [Chatham/Vault.NET#20] opened 2018-05-09 10:19 UTC
When initializing several **_VaultHttpClient_** the **_Accept_** header is duplicated.
This issue is related to issue #19 

### Steps to reproduce:
Initialize several **_VaultHttpClient_** and call the client.

> var client1 = new VaultHttpClient();
var client2 =new VaultHttpClient();
client2.Get<MyObject>(someUri, someVaultToken, someWrapTtl, someCancellationToken)

The Http Request will contain **_Accept_** header with duplicate **_application/json_** values:

`Accept: application/json, application/json, application/json, application/json, application/json`

### Solution:
Initialize the **_VaultHttpClient_** in a **_static block_**:

        static VaultHttpClient()
        {
            HttpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

**Comment by chrishoffman** [comment] 2018-05-16 03:59
Duplicate of #19

**Closed as completed by chrishoffman** 2018-05-16 03:59 UTC
